### ISSUE TITLE
请问如何使用？

### ISSUE THREAD

**Issue by sunnytt98** [fan-chao/nvjmi#12]
假如要进行RTSP转码，是需要使用NVIDIA的ffmpeg先将RTSP转为H.264吗？

**Comment by fan-chao** [comment]
RTSP是一种视频传输协议，跟视频编解码没有关系。这个库只针对解码阶段，至于RTSP流如何接收可以使用ffmpeg也可以使用live555等库实现。

**Comment by sunnytt98** [comment]
> RTSP是一种视频传输协议，跟视频编解码没有关系。这个库只针对解码阶段，至于RTSP流如何接收可以使用ffmpeg也可以使用live555等库实现。

您好，感谢您的回复。
我看您API里 
JMI_API int nvjmi_decoder_put_packet(nvJmiCtx* ctx, nvPacket* packet)输入的是nvPacket
请问这个数据格式具体怎么获取。目前我可以使用FFmpeg将RTSP解码为H.264。
不清楚怎么在这个基础上调用您写的API。

**Comment by fan-chao** [comment]
可以参考https://github.com/fan-chao/nvjmi/issues/1。

**Comment by sunnytt98** [comment]
> 可以参考[https://github.com/fan-chao/nvjmi/issues/1。](https://github.com/fan-chao/nvjmi/issues/1%E3%80%82)
非常感谢您的解答，我正在使用您给的参考进行调试。

**Comment by sunnytt98** [comment]
> 
作者您好，根据您昨天给的示例，我使用FFmpeg进行取流进行解码。
代码如下：
`if (av_read_frame(pFormatCtx, packet) >= 0)

        {
            if (packet->stream_index == videoindex)
            {
                cout << "data size is:" << packet->size<<endl;
                int ret{};
                nvPacket nvpacket;
                nvpacket.payload_size = packet->size;//数据的大小
                nvpacket.payload = packet->data;//数据
                ret = nvjmi_decoder_put_packet(jmi_ctx_, &nvpacket);
                if(ret == NVJMI_ERROR_STOP)
                {
                    printf("frameCallback: nvjmi decode error, frame callback EOF!");
                }
                nvFrameMeta nvframe_meta;
                if (ret>=0)
                {
                    ret = nvjmi_decoder_get_frame_meta(jmi_ctx_, &nvframe_meta);
                    cout<<ret<<endl;
                    if (ret < 0)
                        break;
                    int *p = new int[1920*1080*3];
                    jmi::nvjmi_decoder_retrieve_frame_data(jmi_ctx_, &nvframe_meta, (void*)p);
                    fwrite(packet-> data, 1, packet->size, fpSave);
                }
            }
            av_packet_unref(packet);
        }`
但是运行到这一步
`  ret = nvjmi_decoder_get_frame_meta(jmi_ctx_, &nvframe_meta);`
提示NVJMI_ERROR_FRAMES_EMPTY  ret=-6
请问是我输入的数据有问题吗？

**Comment by fan-chao** [comment]
解码后的缓存队列里没有数据，通过调试可以查看一下。

**Comment by sunnytt98** [comment]
> 

作者您好。
我的平台是jetson nano。目前已经可以正常解码。现在遇到一个问题，在解码过程中内存的使用率会缓慢增加。

```
 unsigned char *p  = new unsigned char [1080*1920*3];  
 ret = jmi::nvjmi_decoder_retrieve_frame_data(jmi_ctx_, &nvframe_meta, (void *)p);  
 delete []p;
```
请问是我这样开辟区域有问题吗？

**Comment by fan-chao** [comment]
解码时使用了多个队列，队列大小有限，可以看看是不是内存增长到某个值就不增长了。另外，可以使用一些内存工具查找内存泄漏点。

**Comment by sunnytt98** [comment]
> 解码时使用了多个队列，队列大小有限，可以看看是不是内存增长到某个值就不增长了。另外，可以使用一些内存工具查找内存泄漏点。

感谢作者这几天的指导与帮助，内存泄漏问题是FFmpeg导致的，已经排查到问题了。
