### ISSUE TITLE
转化到mat的图色彩空间不对

### ISSUE THREAD

**Issue by a514154639** [fan-chao/nvjmi#15]
你好，我根据您给的demo测试的时候，最终的转化的完的mat色彩空间有点问题，我记得您在dec中最终完成了RGBA->BGR的转化，我的代码是这样的
![image](https://github.com/user-attachments/assets/16793821-6f8d-448f-875c-816918576676)
        最终获得的mat是
![image](https://github.com/user-attachments/assets/230a4f21-f319-4aea-b21f-2b5346b911a5)
这是哪里出了问题

**Comment by fan-chao** [comment]
试试下面这个呢
cv::Mat(nvframe_meta.height, nvframe_meta.width, CV_8UC3, buffer, nvframe_meta.payload_size / nvframe_meta.height);

**Comment by a514154639** [comment]
> 试试下面这个呢 cv::Mat(nvframe_meta.height, nvframe_meta.width, CV_8UC3, buffer, nvframe_meta.payload_size / nvframe_meta.height);

修改之后还是这样的，不知道是通道的问题还是什么，您的demo里那个Buffer是什么数据结构呢？

**Comment by fan-chao** [comment]
这个库的jetpack有版本要求，看看jetpack版本对不对。

**Comment by fan-chao** [comment]
最新的jetpack版本可以参考使用https://github.com/Keylost/jetson-ffmpeg，这个直接使用ffmpeg的API解码。

**Comment by a514154639** [comment]
> 最新的jetpack版本可以参考使用[https://github.com/Keylost/jetson-ffmpeg，这个直接使用ffmpeg的API解码。](https://github.com/Keylost/jetson-ffmpeg%EF%BC%8C%E8%BF%99%E4%B8%AA%E7%9B%B4%E6%8E%A5%E4%BD%BF%E7%94%A8ffmpeg%E7%9A%84API%E8%A7%A3%E7%A0%81%E3%80%82)

我的版本是4.6 我把common和include的内容都复制过来了，这个项目硬解码到的avframe是在cpu上，色彩空间转化CPU消耗太高了

**Comment by fan-chao** [comment]
> > 最新的jetpack版本可以参考使用[https://github.com/Keylost/jetson-ffmpeg，这个直接使用ffmpeg的API解码。](https://github.com/Keylost/jetson-ffmpeg%EF%BC%8C%E8%BF%99%E4%B8%AA%E7%9B%B4%E6%8E%A5%E4%BD%BF%E7%94%A8ffmpeg%E7%9A%84API%E8%A7%A3%E7%A0%81%E3%80%82)
> 
> 我的版本是4.6 我把common和include的内容都复制过来了，这个项目硬解码到的avframe是在cpu上，色彩空间转化CPU消耗太高了

可以使用https://github.com/CVCUDA/CV-CUDA的cvt_corlor进行硬件的色彩空间转换。

**Comment by a514154639** [comment]
> > > 最新的jetpack版本可以参考使用[https://github.com/Keylost/jetson-ffmpeg，这个直接使用ffmpeg的API解码。](https://github.com/Keylost/jetson-ffmpeg%EF%BC%8C%E8%BF%99%E4%B8%AA%E7%9B%B4%E6%8E%A5%E4%BD%BF%E7%94%A8ffmpeg%E7%9A%84API%E8%A7%A3%E7%A0%81%E3%80%82)
> > 
> > 
> > 我的版本是4.6 我把common和include的内容都复制过来了，这个项目硬解码到的avframe是在cpu上，色彩空间转化CPU消耗太高了
> 
> 可以使用[https://github.com/CVCUDA/CV-CUDA的cvt_corlor进行硬件的色彩空间转换。](https://github.com/CVCUDA/CV-CUDA%E7%9A%84cvt_corlor%E8%BF%9B%E8%A1%8C%E7%A1%AC%E4%BB%B6%E7%9A%84%E8%89%B2%E5%BD%A9%E7%A9%BA%E9%97%B4%E8%BD%AC%E6%8D%A2%E3%80%82)

大佬这个库好像失效了，我用他那个项目自己实现过CUDA进行色彩转化，但是拷贝耗时太高了，他硬解码出的数据没在GPU上，和原生的sws_scale时间差不多

**Comment by fan-chao** [comment]
> > > > 最新的jetpack版本可以参考使用[https://github.com/Keylost/jetson-ffmpeg，这个直接使用ffmpeg的API解码。](https://github.com/Keylost/jetson-ffmpeg%EF%BC%8C%E8%BF%99%E4%B8%AA%E7%9B%B4%E6%8E%A5%E4%BD%BF%E7%94%A8ffmpeg%E7%9A%84API%E8%A7%A3%E7%A0%81%E3%80%82)
> > > 
> > > 
> > > 我的版本是4.6 我把common和include的内容都复制过来了，这个项目硬解码到的avframe是在cpu上，色彩空间转化CPU消耗太高了
> > 
> > 
> > 可以使用[https://github.com/CVCUDA/CV-CUDA的cvt_corlor进行硬件的色彩空间转换。](https://github.com/CVCUDA/CV-CUDA%E7%9A%84cvt_corlor%E8%BF%9B%E8%A1%8C%E7%A1%AC%E4%BB%B6%E7%9A%84%E8%89%B2%E5%BD%A9%E7%A9%BA%E9%97%B4%E8%BD%AC%E6%8D%A2%E3%80%82)
> 
> 大佬这个库好像失效了，我用他那个项目自己实现过CUDA进行色彩转化，但是拷贝耗时太高了，他硬解码出的数据没在GPU上，和原生的sws_scale时间差不多

是这个CV-CUDA的库，https://github.com/CVCUDA/CV-CUDA
另外，在jetson上，cpu和gpu的内存是同一个，可以使用零拷贝方式拷贝数据是基本不耗时的。

**Comment by a514154639** [comment]
> > > > > 最新的jetpack版本可以参考使用[https://github.com/Keylost/jetson-ffmpeg，这个直接使用ffmpeg的API解码。](https://github.com/Keylost/jetson-ffmpeg%EF%BC%8C%E8%BF%99%E4%B8%AA%E7%9B%B4%E6%8E%A5%E4%BD%BF%E7%94%A8ffmpeg%E7%9A%84API%E8%A7%A3%E7%A0%81%E3%80%82)
> > > > 
> > > > 
> > > > 我的版本是4.6 我把common和include的内容都复制过来了，这个项目硬解码到的avframe是在cpu上，色彩空间转化CPU消耗太高了
> > > 
> > > 
> > > 可以使用[https://github.com/CVCUDA/CV-CUDA的cvt_corlor进行硬件的色彩空间转换。](https://github.com/CVCUDA/CV-CUDA%E7%9A%84cvt_corlor%E8%BF%9B%E8%A1%8C%E7%A1%AC%E4%BB%B6%E7%9A%84%E8%89%B2%E5%BD%A9%E7%A9%BA%E9%97%B4%E8%BD%AC%E6%8D%A2%E3%80%82)
> > 
> > 
> > 大佬这个库好像失效了，我用他那个项目自己实现过CUDA进行色彩转化，但是拷贝耗时太高了，他硬解码出的数据没在GPU上，和原生的sws_scale时间差不多
> 
> 是这个CV-CUDA的库，https://github.com/CVCUDA/CV-CUDA 另外，在jetson上，cpu和gpu的内存是同一个，可以使用零拷贝方式拷贝数据是基本不耗时的。

好的 谢谢大佬 我再去看一下
