### ISSUE TITLE
不连接显示器的情况下  解码出来的数据是空的

### ISSUE THREAD

**Issue by mahxn0** [fan-chao/nvjmi#2]
NvEGLImageFromFd: No EGLDisplay to create EGLImage
Error while mapping dmabuf fd (1539) to EGLImage

请问有啥设置可以在不连接显示器的情况下正常运行吗

**Comment by fan-chao** [comment]
1）nvbuf_utils: Could not get EGL display connection
    并且eglGetDisplay(EGL_DEFAULT_DISPLAY)返回NULL？
解决方案：
    1>在ssh终端输入unset DISPLAY，然后再运行程序即可。
    2>vim /etc/profile，添加unset DISPLAY，然后souce /etc/profile生效，然后重启机器reboot。

**Comment by mahxn0** [comment]
可以了  感谢大佬
