### ISSUE TITLE
为什么在多路解码的时候运行一会就会到这里面呢    jmi::NVJMI_ERROR_STOP

### ISSUE THREAD

**Issue by mahxn0** [fan-chao/nvjmi#3]
jmi::nvPacket nvpacket;

nvpacket.payload_size = dataLen;
nvpacket.payload = data;

int ret{};
ret = jmi::nvjmi_decoder_put_packet(jmi_ctx_, &nvpacket);
if(ret == jmi::NVJMI_ERROR_STOP) {
    LOG_INFO(VDO_RTSP_LOG, "[{}] frameCallback: nvjmi decode error, frame callback EOF!", m_ip);
}

while (ret >= 0) {
    jmi::nvFrameMeta nvframe_meta;
    ret = jmi::nvjmi_decoder_get_frame_meta(jmi_ctx_, &nvframe_meta);
    if (ret < 0) break;

    Buffer buf;
    buf.allocate(nvframe_meta.width, nvframe_meta.height, 3, nvframe_meta.payload_size / nvframe_meta.height);
    jmi::nvjmi_decoder_retrieve_frame_data(jmi_ctx_, &nvframe_meta, (void*)buf.getData());     
}

**Comment by mahxn0** [comment]
方便加个微信有偿指导一下吗18392418428

**Comment by fan-chao** [comment]
估计是线程问题，每一路最好单独启一个线程，有源码，可以调试看一下。

**Comment by mahxn0** [comment]
> 估计是线程问题，每一路最好单独启一个线程，有源码，可以调试看一下。

OK  我先调试看看  目前来看jetson  nx 8路没问题  但是16路就会有这个问题

**Comment by mahxn0** [comment]
你好  有遇到过解码花屏的问题吗  我1路保存图片 偶尔中间会出现花屏   16路更加严重  是不是需要手动刷dma的cache

**Comment by fan-chao** [comment]
我这边没遇到过花屏。rtsp接入时有没有丢帧，或者通过使用视频文件测试看看会不会同样丢帧。
