### ISSUE TITLE
请问大佬，出现这种错误可能是什么原因？

### ISSUE THREAD

**Issue by thunder95** [fan-chao/nvjmi#5]
![Screenshot from 2021-07-06 13-09-10](https://user-images.githubusercontent.com/22673612/124547354-94d1c680-de5e-11eb-820a-c406e2ba6eab.png)

**Comment by fan-chao** [comment]
如果是transform报错，可以检查下传入的参数是否正确。

**Comment by thunder95** [comment]
> 如果是transform报错，可以检查下传入的参数是否正确。

@fan-chao 非常感谢回复。 参数应该是对的，我现在的情况是，这错误出现的频次并不高， 而且2路摄像头也还ok基本没发现这种错误， 5路摄像头解码就出现的多一些，但最终摄像头还能正常运行。

**Comment by fan-chao** [comment]
这种情况可以看看硬件资源是不是不够用了，因为transform使用的也是硬件nvhost-vic执行的。

**Comment by thunder95** [comment]
> 这种情况可以看看硬件资源是不是不够用了，因为transform使用的也是硬件nvhost-vic执行的。

好像是这样， 我屏蔽掉下游的算法处理之后，也基本不报这个错了。
