### ISSUE TITLE
作者你好，能不能提供一个比较完整的调用demo

### ISSUE THREAD

**Issue by zjhellofss** [fan-chao/nvjmi#6]
如题，非常感谢！！

**Comment by fan-chao** [comment]
Demo可以参考这个https://github.com/fan-chao/nvjmi/issues/1 实现。

**Comment by zjhellofss** [comment]
> Demo可以参考这个[https://github.com/fan-chao/nvjmi/issues/1实现。](https://github.com/fan-chao/nvjmi/issues/1%E5%AE%9E%E7%8E%B0%E3%80%82)

我看了一下，但是我是一个视频编解码的小白，对一个地方不太明白
jmi::nvPacket nvpacket;
```
nvpacket.payload_size = dataLen;
nvpacket.payload = data;

```
这处地方的data是从哪里来的，从哪里读取到的。能不能讲解一下

**Comment by fan-chao** [comment]
这个data就是原始码流的数据帧，类似ffmpeg里的packet，datalen是这一帧的数据大小。

**Comment by zjhellofss** [comment]
> 

好的，明白了。谢谢大佬
