### ISSUE TITLE
请教一个问题，本项目的nvdec解码是否用到了cuda，如果用到的话能不能让解码得到的数据存放于cuda的显存中

### ISSUE THREAD

**Issue by zjhellofss** [fan-chao/nvjmi#8]
如题，非常感谢

**Comment by fan-chao** [comment]
// do CUDA conversion: RGBA packed@res#2 --> BGR planar@res#2
                    ctx->cuda_converter->convert(egl_frame,
                        ctx->resize_width,
                        ctx->resize_height,
                        COLOR_FORMAT_BGR,
                        (void *)ctx->frame_buffer[buf_index],
                        ctx->cuda_stream);

                    cudaStreamSynchronize(ctx->cuda_stream);
这个地方的缓冲区的指针(void *)ctx->frame_buffer[buf_index]就是GPU上的存储区域。

**Comment by zjhellofss** [comment]
我看了一下代码，是不是可以这样理解
从
```cpp

    JMI_API int nvjmi_decoder_retrieve_frame_data(nvJmiCtx *ctx, nvFrameMeta *frame_meta, void *frame_data)
    {
        if (frame_data)
        {
            memcpy((unsigned char *)frame_data, ctx->frame_buffer[frame_meta->frame_index], frame_meta->payload_size);
            frame_meta->got_data = 1;
        }

        while (!ctx->frame_pools->try_push(frame_meta->frame_index) && !ctx->capture_plane_stop)
        {
            std::this_thread::yield();
        }
        return NVJMI_OK;
    }
```
中获取的`void *frame_data`是一个既**指向主存又指向显存**的指针

**Comment by fan-chao** [comment]
是的，jetson如果使用特定的cuda接口分配内存，cpu和gpu的指针是一样的，实现了零拷贝。可以参考https://github.com/fan-chao/cuda_utils/blob/main/source/cuda/cudaMappedMemory.h 里面的内存分配方式。

**Comment by zjhellofss** [comment]
我明白了，大佬
